/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as RiftRouteImport } from './routes/rift'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as BazaarRouteImport } from './routes/bazaar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminEntitiesRouteImport } from './routes/admin/entities'
import { Route as AdminBazaarRouteImport } from './routes/admin/bazaar'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const RiftRoute = RiftRouteImport.update({
  id: '/rift',
  path: '/rift',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const BazaarRoute = BazaarRouteImport.update({
  id: '/bazaar',
  path: '/bazaar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntitiesRoute = AdminEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBazaarRoute = AdminBazaarRouteImport.update({
  id: '/bazaar',
  path: '/bazaar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bazaar': typeof BazaarRoute
  '/collection': typeof CollectionRoute
  '/profile': typeof ProfileRoute
  '/rift': typeof RiftRoute
  '/vault': typeof VaultRoute
  '/admin/bazaar': typeof AdminBazaarRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bazaar': typeof BazaarRoute
  '/collection': typeof CollectionRoute
  '/profile': typeof ProfileRoute
  '/rift': typeof RiftRoute
  '/vault': typeof VaultRoute
  '/admin/bazaar': typeof AdminBazaarRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bazaar': typeof BazaarRoute
  '/collection': typeof CollectionRoute
  '/profile': typeof ProfileRoute
  '/rift': typeof RiftRoute
  '/vault': typeof VaultRoute
  '/admin/bazaar': typeof AdminBazaarRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bazaar'
    | '/collection'
    | '/profile'
    | '/rift'
    | '/vault'
    | '/admin/bazaar'
    | '/admin/entities'
    | '/admin/logs'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bazaar'
    | '/collection'
    | '/profile'
    | '/rift'
    | '/vault'
    | '/admin/bazaar'
    | '/admin/entities'
    | '/admin/logs'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bazaar'
    | '/collection'
    | '/profile'
    | '/rift'
    | '/vault'
    | '/admin/bazaar'
    | '/admin/entities'
    | '/admin/logs'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BazaarRoute: typeof BazaarRoute
  CollectionRoute: typeof CollectionRoute
  ProfileRoute: typeof ProfileRoute
  RiftRoute: typeof RiftRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rift': {
      id: '/rift'
      path: '/rift'
      fullPath: '/rift'
      preLoaderRoute: typeof RiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazaar': {
      id: '/bazaar'
      path: '/bazaar'
      fullPath: '/bazaar'
      preLoaderRoute: typeof BazaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entities': {
      id: '/admin/entities'
      path: '/entities'
      fullPath: '/admin/entities'
      preLoaderRoute: typeof AdminEntitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bazaar': {
      id: '/admin/bazaar'
      path: '/bazaar'
      fullPath: '/admin/bazaar'
      preLoaderRoute: typeof AdminBazaarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBazaarRoute: typeof AdminBazaarRoute
  AdminEntitiesRoute: typeof AdminEntitiesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBazaarRoute: AdminBazaarRoute,
  AdminEntitiesRoute: AdminEntitiesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BazaarRoute: BazaarRoute,
  CollectionRoute: CollectionRoute,
  ProfileRoute: ProfileRoute,
  RiftRoute: RiftRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
